name: Deployment
on:
  push:
    branches:
      - 'master'
jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Install Node v14
        uses: actions/setup-node@master
        with:
          node-version: 14

      - name: Install dependencies
        run: npm i --also=dev

      - name: Build and deploy documentation
        uses: discordjs/action-docs@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}